[tool.poetry]
name = "queuebot"
version = "1.4.11"
description = ""
authors = ["Sarioah <3851003+Sarioah@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
keyring = "^25.1.0"
colorama = "^0.4.6"
readchar = "^4.0.6"
aiohttp = "^3.13.3"
pywin32 = "^306"
irc = "20.4.0"


[tool.poetry.group.dev.dependencies]
black = "^24.4.0"
nuitka = "^2.1.5"
coverage = "^7.4.4"

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain if non-runnable code isn't run:
    "if __name__ == .__main__.:",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
