[tool.poetry]
name = "queuebot"
version = "1.4.13"
description = ""
authors = ["Sarioah <3851003+Sarioah@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
keyring = "^25.7.0"
colorama = "^0.4.6"
readchar = "^4.2.1"
aiohttp = "^3.13.3"
pywin32 = "^311"
irc = "20.4.0" # 20.5 fights with importlib-resources on freeze
setuptools = "^80.9.0"
tempora = "~5.6" # 5.7+ pulls in dateutil which causes warnings on freeze


[tool.poetry.group.dev.dependencies]
black = "^25.12.0"
nuitka = "^2.8.9"
coverage = "^7.13.1"

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain if non-runnable code isn't run:
    "if __name__ == .__main__.:",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
